export const ELEMENTS = {
  imageSourceLoading:
    '[class*="loading"] [class*="loading-img"] [class*="icon-spinner"]',
  buttonCalculateShipping: '[class*="shipping-calculate-link"]',
  buttonCartToOrder: '[class*="btn-place-order"]',
  buttonCartToOrderForm: '[class*="btn-place-order"]',
  buttonReturnToCart: '[class*="link-cart"]',
  divCartFull: '[class*="cart-items"]',
  divCartEmpty: '[class*="empty-cart-content"]',
  inputCoupon: '[class*="coupon-value"]',
  inputZipCode: '[class*="srp-data"] input',
  labelShippingAvailable: '[class*="srp-result"]',
  buttonCouponAdd: '[class*="coupon"] [class*="btn"]',
  msgInvalidDiscountCoupon: '[class*="vtex-front-messages-template"]',
  buttonItemRemoveProduct: '[class*="item-link-remove"]',
  imageSourceProduct: (product) =>
    `[class*="product-item"] img[alt*="${product}"]`,
  buttonIncrementQuantity: '[class*="item-quantity-change-increment"]',
  buttonDecrementQuantity: '[class*="item-quantity-change-decrement"]',
  labelItemQuantity: '[class*="product-item"] input[type="tel"]',
  shippingButton: '[class*="shipping-calculate-link"]',
  linkCoupon: '[class*="coupon"] [class*="coupon-data"]',
  unavailableShippingData: '[class*="srp-unavailable"]',
  addedValidCoupon: '[class*="coupon-fields"] [class*="info"]',
  homeBackButton: '[class*="backButton"]',
  cartRow: '[class*="product-item"]',
}
